import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({
    subsets: ['latin'], // Optionally add other subsets like 'latin-ext' or 'cyrillic'
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${inter.className} antialiased bg-[#ebece7] text-black`}
        >
        <Navbar/>
        <main className={"max-w-dvw max-h-[calc(100dvh-104px)] w-full h-dvh"}>
            {children}
        </main>
        </body>
        </html>
    );
}
